DAG:
    dag_id: example_dag
    args:
        description: this is a example dag configuration
        max_active_runs: 1
        schedule: 0 * * * *
        catchup: !!bool False
        default_args:
            depends_on_past: !!bool False
            start_date: !!python/object/apply:datetime.datetime [2023, 3, 8]
            email:
              - longnguyen@behmd.com
            email_on_failure: !!bool True
            email_on_retry: !!bool False
            retries: 1
            retry_delay: !!python/object/new:datetime.timedelta
              kwds: {minutes: 1}
            sla: !!python/object/new:datetime.timedelta
              kwds: {hours: 1}
    tasks:
        start_point:
            operator: !!python/name:airflow.operators.dummy_operator.DummyOperator
        ingest_data_from_db:
            operator: !!python/name:airflow.operators.bash_operator.BashOperator
            args:
              bash_command: "python {{ingest_data}}"
            upstream:
              - start_point
        transform_data:
            operator: !!python/name:airflow.operators.bash_operator.BashOperator
            args:
              bash_command: "python {{transform_data}}"
            upstream:
              - ingest_data_from_db